name: matthewhamer.co.uk
favicon: null
layout_spectrum: 0.49398
typography_spectrum: 0.65523
title: 'Matthew Hamer | LSM Operator based in Manchester'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
